version: '3.3'
services:
  test-d3m-primitives:
    build: .
    container_name: test-d3m-primitives
    stdin_open: true
    tty: true
    env_file:
    - .env
    entrypoint: /bin/bash
    volumes:
    - ${DATASETS}:/datasets
    - ./:/d3m-primitives
