ALL_KNOWN_KEY = 'all_known'
ALL_UNKNOWN_KEY = 'all_unknown'
SOME_KNOWN_KEY = 'some_known'
CLASSIFICATION_DATASET_NAME = '38_sick'
COL_NAME_KEY = 'name'
DEFAULT_DATASET_DIR = '/datasets/training_datasets/LL0'
DATASETS_DIR = '/datasets/seed_datasets_current'
